### ISSUE TITLE
showEllipsis gets ignored

### ISSUE THREAD

**Issue by 1N50MN14** [DevCrew-io/expandable-richtext#21]
Hello,

Thank you for the package. I'm trying to set `showEllipsis` to `false` which seems get ignored.  To reproduce, simply falsify it. Running package version `1.0.3`.

Thanks

**Comment by WaseemAbbas-DevCrew** [comment]
Nice catch @1N50MN14 :+1:
Looks like when we set the `showEllipsis: false` it makes the `...` chracter as a part of the `see more` link. I deally it should be hidden when the this value is set to `false` and visible when `true`.

**Comment by WaseemAbbas-DevCrew** [comment]
@1N50MN14 The issue has been fixed
