### ISSUE TITLE
Max lines, is not consistent

### ISSUE THREAD

**Issue by MuhammadIbrahimSE** [DevCrew-io/expandable-richtext#26]
Sometimes, it even shows read more after half line and sometimes it shows after two lines.

**Comment by AlexUrrutia** [comment]
Yes, it has to be fixed...

**Comment by WaseemAbbas-DevCrew** [comment]
@minhajdevcrew can you please look into this?

**Comment by WaseemAbbas-DevCrew** [comment]
this issue has been fixed.
