### ISSUE TITLE
Support the textScaler parameter.

### ISSUE THREAD

**Issue by darkstarx** [DevCrew-io/expandable-richtext#34]
Hi!
`RichText` that you use inside doesn't automatically apply system text size, it needs `textScaler` from the `MediaQuery`. Could you provide the access to this parameter from the `ExpandableRichText`, please?

**Comment by minhajdevcrew** [comment]
@darkstarx Thank you for noticing this issue. We have acknowledged it and fixed it in version v1.0.7.

**Comment by darkstarx** [comment]
Great, thanks a lot!
